default: &default
  host: <%= ENV['STOMP_HOST'] %>
  port: <%= ENV['STOMP_PORT'] %>
  max_reconnect_attempts: 5
  max_retry_attempts: 5
  archelon_url: <%= ENV['ARCHELON_URL'] %>
  destinations:
    jobs: /queue/plastron.jobs
    job_progress: /topic/plastron.jobs.progress
    job_status: /queue/plastron.jobs.status
    jobs_synchronous: /queue/plastron.jobs.synchronous

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
